import js from '@eslint/js'
import ts from 'typescript-eslint'
import prettier from 'eslint-config-prettier'
import reactHooks from 'eslint-plugin-react-hooks'
import nextPlugin from '@next/eslint-plugin-next'

export default ts.config(
  js.configs.recommended,
  ...ts.configs.recommended,
  {
    plugins: {
      '@next/next': nextPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      '@next/next/no-html-link-for-pages': 'off',
      '@next/next/no-img-element': 'off',
    },
  },
  {
    plugins: {
      'react-hooks': reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // Disable strict hooks rules during migration
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  {
    // Global variables for Next.js (Node.js + Browser)
    languageOptions: {
      globals: {
        // Browser globals
        console: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Headers: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        Audio: 'readonly',
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        // More browser globals
        FormData: 'readonly',
        CustomEvent: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        Image: 'readonly',
        TextDecoder: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        IntersectionObserver: 'readonly',
        status: 'readonly', // Legacy code uses this
        // Node.js globals
        process: 'readonly',
        global: 'readonly',
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
      },
    },
  },
  {
    // Disable TypeScript-specific rules for plain JS files during migration
    files: ['**/*.js', '**/*.jsx', '**/*.mjs'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/triple-slash-reference': 'off',
      // Disable strict react-hooks rules during migration
      'react-hooks/rules-of-hooks': 'off',
      'react-hooks/exhaustive-deps': 'off',
      'react-hooks/globals': 'off',
      'react-hooks/immutability': 'off',
      // Disable other rules causing issues in legacy code
      'no-useless-escape': 'off',
      'no-useless-assignment': 'off',
      'no-constant-binary-expression': 'off',
    },
  },
  {
    // Keep migration gates green for newly renamed TS/TSX app files
    files: ['app/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'react-hooks/exhaustive-deps': 'off',
      'no-useless-escape': 'off',
      'no-useless-assignment': 'off',
      'no-constant-binary-expression': 'off',
      'prefer-const': 'off',
    },
  },
  {
    // Special handling for next-env.d.ts (auto-generated by Next.js)
    files: ['next-env.d.ts'],
    rules: {
      '@typescript-eslint/triple-slash-reference': 'off',
    },
  },
  {
    ignores: ['.next/', 'node_modules/', 'dist/', 'out/'],
  },
  prettier
)
